### ISSUE TITLE
Verkar fungera bra

### ISSUE THREAD

**Issue by reMRKableDev** [coglescode/search#1]
@coglescode Jag har kollat på koden och det fungerar på vscode. Jag bifogar videon med vad jag menar. Let me know om det är något som jag har missat

https://www.loom.com/share/b1b984f539cf4c418596ac0d85708831

**Comment by coglescode** [comment]
Hej
Gud va konstigt att det fungerade för dig. Jag gick genom igen på allt speciellt på länken till css filen som du hade undrat …

Den här är samma kod jag skickade till dig 
<link rel=”stylesheet” href=”../ccs/main.css” type=”text/css”>

right …

Now så här fungerar för mig
<link rel=”stylesheet” href=”./ccs/main.css” type=”text/css”>

Vet inte vrf hände detta, tog bort bara en punkt  och började att fungera, även med två punkt  om jag gör crtl+click leder länken till css filen men ändå stylen visas inte.

Men iaf tack so hemskt mycket för att du tog din tid med att hjälpa mig med detta och tack för tipsen om Live Server och Loom försökte att göra en video men det gick för mig. 
Vill veta om du föredrar engelska eller svenska för framtida kontakt? 

THANKS for the help!
Leo 


 

Sent from Mail for Windows 10

From: Malcolm R. Kente
Sent: 23 July 2020 11:58
To: coglescode/search
Cc: coglescode; Mention
Subject: [coglescode/search] Verkar fungera bra (#1)

@coglescode Jag har kollat på koden och det fungerar på vscode. Jag bifogar videon med vad jag menar. Let me know om det är något som jag har missat
https://www.loom.com/share/b1b984f539cf4c418596ac0d85708831

**Comment by reMRKableDev** [comment]
```<link rel=”stylesheet” href=”./ccs/main.css” type=”text/css”>``` 

Punkterna har att göra med 'paths'/vägar som filerna ligger i projektet:
- En punkt innebar att filen ligger en väg tilllbaka
- Två innebär att filen ligger 2 väggar tillbaka

Kanke kan dessa hjälpa 
https://stackoverflow.com/questions/12066435/what-do-the-dots-mean-in-relative-file-path

https://www.youtube.com/watch?v=ephId3mYu9o

**Comment by coglescode** [comment]
Okej. Tack for hjälpen.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: "Malcolm R. Kente" <notifications@github.com> Date: 26/07/2020  14:45  (GMT+01:00) To: coglescode/search <search@noreply.github.com> Cc: coglescode <cogles_bonne@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [coglescode/search] Verkar fungera bra (#1) 

<link rel=”stylesheet” href=”./ccs/main.css” type=”text/css”>

Punkterna har att göra med 'paths'/vägar som filerna ligger i projektet:



En punkt innebar att filen ligger en väg tilllbaka

Två innebär att filen ligger 2 väggar tillbaka



Kanke kan dessa hjälpa

https://stackoverflow.com/questions/12066435/what-do-the-dots-mean-in-relative-file-path

https://www.youtube.com/watch?v=ephId3mYu9o

**Comment by reMRKableDev** [comment]
Ingen fara!
Språkmässigt spelar det ingen roll, ibland vet jag att vissa saker är bättre att förklara på engelska än svenska. Men förmodligen kommer jag svara på något av språken beroende på situationen 😀
